### ISSUE TITLE
Tracking changes of our perpetual release candidate

### ISSUE THREAD

**Issue by alalazo** [epfl-scitas/spack#128]
This "living" issue tracks the changes of our internal release candidate with respect to upstream.

# Core framework + CI

- [x] #127 (custom target types)
- [x] #126 which is https://github.com/spack/spack/pull/5842 (no unit tests on packages)
- [x] #132 (no MacOS builds on develop, only once per day during a cron job)
- [x] #133 (added flag filtering to report status)
- [x] #161 which is https://github.com/spack/spack/pull/7868 (`spack compiler add` can register automatically spack built compilers)
- [x] #162 which is https://github.com/spack/spack/pull/7760 (packages can customize the list of files to be archived)
- [x] #163 which is https://github.com/spack/spack/pull/7899 (spack filter command to filter specs that are not installed)
- [x] #168 which is https://github.com/spack/spack/pull/8038 (Package.installed now checks both the presence of prefix and a DB entry)

# Packages

- [x] ~#134 (FFTW with additional SIMD + FMA optimizations) which is https://github.com/spack/spack/pull/7038~

**Comment by alalazo** [comment]
@rmsds Closing this old issue as outdated
